Repository ALLHUBS-Jan-2024-Liftoff/Web-Wizards, pull requests merged in 2024-07, with the labels that each got.

#6 Create gitignoreFromPhillip
  gitignoreFromPhillip
Labels: Dependency/Property Addition

#15 Add files via upload
  Show-Me-Events/HELP.md
  Show-Me-Events/build.gradle
  Show-Me-Events/gradle/wrapper/gradle-wrapper.jar
  Show-Me-Events/gradle/wrapper/gradle-wrapper.properties
  Show-Me-Events/gradlew
  Show-Me-Events/gradlew.bat
  Show-Me-Events/settings.gradle
  Show-Me-Events/src/main/java/org/launchcode/Show_Me/Events/ShowMeEventsApplication.java
  Show-Me-Events/src/main/resources/application.properties
  Show-Me-Events/src/test/java/org/launchcode/Show_Me/Events/ShowMeEventsApplicationTests.java
Labels: Dependency/Property Addition

#20 Add files via upload
  Web-Wizards-Back-End/HELP.md
  Web-Wizards-Back-End/build.gradle
  Web-Wizards-Back-End/build/classes/java/main/org/launchcode/Web_Wizards/Back/End/WebWizardsBackEndApplication.class
  Web-Wizards-Back-End/build/classes/java/test/org/launchcode/Web_Wizards/Back/End/WebWizardsBackEndApplicationTests.class
  Web-Wizards-Back-End/build/resources/main/application.properties
  Web-Wizards-Back-End/build/tmp/compileJava/previous-compilation-data.bin
  Web-Wizards-Back-End/build/tmp/compileTestJava/previous-compilation-data.bin
  Web-Wizards-Back-End/gradle/wrapper/gradle-wrapper.jar
  Web-Wizards-Back-End/gradle/wrapper/gradle-wrapper.properties
  Web-Wizards-Back-End/gradlew
  Web-Wizards-Back-End/gradlew.bat
  Web-Wizards-Back-End/settings.gradle
  Web-Wizards-Back-End/src/main/java/org/launchcode/Web_Wizards/Back/End/WebWizardsBackEndApplication.java
  Web-Wizards-Back-End/src/main/resources/application.properties
  Web-Wizards-Back-End/src/test/java/org/launchcode/Web_Wizards/Back/End/WebWizardsBackEndApplicationTests.java
Labels: enhancement

#24 Add files via upload
  Show-MO-events-BackEnd/HELP.md
  Show-MO-events-BackEnd/build.gradle
  Show-MO-events-BackEnd/build/classes/java/main/org/launchcode/BackEnd/BackEndApplication.class
  Show-MO-events-BackEnd/build/classes/java/test/org/launchcode/BackEnd/BackEndApplicationTests.class
  Show-MO-events-BackEnd/build/resolvedMainClassName
  Show-MO-events-BackEnd/build/resources/main/application.properties
  Show-MO-events-BackEnd/build/tmp/compileJava/previous-compilation-data.bin
  Show-MO-events-BackEnd/build/tmp/compileTestJava/previous-compilation-data.bin
  Show-MO-events-BackEnd/gradle/wrapper/gradle-wrapper.jar
  Show-MO-events-BackEnd/gradle/wrapper/gradle-wrapper.properties
  Show-MO-events-BackEnd/gradlew
  Show-MO-events-BackEnd/gradlew.bat
  Show-MO-events-BackEnd/settings.gradle
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/BackEndApplication.java
  Show-MO-events-BackEnd/src/main/resources/application.properties
  Show-MO-events-BackEnd/src/test/java/org/launchcode/BackEnd/BackEndApplicationTests.java
Labels: enhancement

#27 Updated Front end base
  Show-MO-events/.eslintrc.cjs
  Show-MO-events/.gitignore
Labels: enhancement

#26 adding structure for Java Login form portion
  .idea/.gitignore
  .idea/Web-Wizards.iml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/controllers/AuthenticationController.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/AbstractEntity.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/User.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/data/UserRepository.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/dto/LoginFormDTO.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/dto/RegisterFormDTO.java
  Show-MO-events-BackEnd/src/main/resources/static/css/bootstrap.css
  Show-MO-events-BackEnd/src/main/resources/templates/fragments.html
  Show-MO-events-BackEnd/src/main/resources/templates/index.html
  Show-MO-events-BackEnd/src/main/resources/templates/login.html
  Show-MO-events-BackEnd/src/main/resources/templates/register.html
Labels: enhancement

#45 Front end base build- Base file structure for adding features.
  Show-MO-events-BackEnd/.gradle/8.8/executionHistory/executionHistory.bin
  Show-MO-events-BackEnd/.gradle/8.8/executionHistory/executionHistory.lock
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/fileHashes.bin
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/fileHashes.lock
  Show-MO-events-BackEnd/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  Show-MO-events-BackEnd/.gradle/buildOutputCleanup/outputFiles.bin
  Show-MO-events-BackEnd/.gradle/file-system.probe
  Show-MO-events-BackEnd/build/resources/main/static/css/backend.css
  Show-MO-events-BackEnd/src/main/resources/static/css/backend.css
  Show-MO-events/package-lock.json
  Show-MO-events/package.json
  Show-MO-events/src/App.css
  Show-MO-events/src/App.jsx
  Show-MO-events/src/asserts/Cheifs.jpg
  Show-MO-events/src/asserts/KC.jpg
  Show-MO-events/src/asserts/SPOILER_WebWizardTraining.png
  Show-MO-events/src/asserts/react.svg
  Show-MO-events/src/asserts/st-arch.jpg
  Show-MO-events/src/components/LandingPage/AboutMe.jsx
  Show-MO-events/src/components/LandingPage/Contact.jsx
  Show-MO-events/src/components/LandingPage/LoginForm.jsx
  Show-MO-events/src/components/LandingPage/MainPage.jsx
  Show-MO-events/src/components/LandingPage/Navbar.jsx
  Show-MO-events/src/components/LandingPage/Services.jsx
  Show-MO-events/src/components/LandingPage/SlideShow.jsx
  Show-MO-events/src/css/AboutMe.css
  Show-MO-events/src/css/Contact.css
  Show-MO-events/src/css/LoginForm.css
  Show-MO-events/src/css/Navbar.css
  Show-MO-events/src/css/Services.css
  Show-MO-events/src/css/SlideShow.css
  Show-MO-events/src/index.css
  Show-MO-events/src/services/AxiosService.js
Labels: enhancement

#50 Delete .idea directory
  .idea/.gitignore
  .idea/Web-Wizards.iml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
Labels: invalid
