Repository ALLHUBS-Jan-2024-Liftoff/Web-Wizards, pull requests merged in 2024-08, with the labels that each got.

#63 Added Google Login authentication.
  Show-MO-events/src/components/GoogleLogin.jsx
Labels: enhancement

#62 Update to registration form
  Show-MO-events-BackEnd/.gradle/8.8/executionHistory/executionHistory.bin
  Show-MO-events-BackEnd/.gradle/8.8/executionHistory/executionHistory.lock
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/fileHashes.bin
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/fileHashes.lock
  Show-MO-events-BackEnd/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  Show-MO-events-BackEnd/.gradle/buildOutputCleanup/outputFiles.bin
  Show-MO-events-BackEnd/.gradle/file-system.probe
  Show-MO-events-BackEnd/build/tmp/compileJava/previous-compilation-data.bin
  Show-MO-events/src/components/RegistrationForm.jsx
Labels: enhancement

#61 updated login form for api
  Show-MO-events/src/components/LoginForm.jsx
Labels: Dependency/Property Addition

#60 Web api model added to allow 5173 and 8080 to talk
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/WebConfig.java
Labels: enhancement

#59 authentication controller update for Api usage
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/controllers/AuthenticationController.java
Labels: enhancement

#58 Delete Show-MO-events/public/vite.svg
  Show-MO-events/public/vite.svg
Labels: duplicate, invalid

#64 Additional button for Google Login Addition.
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/fileHashes.lock
  Show-MO-events/src/components/Google.css
  Show-MO-events/src/components/GoogleButton.jpg
  Show-MO-events/src/components/GoogleLogin.jsx
  Show-MO-events/src/components/LoginForm.jsx
  Show-MO-events/src/components/RegistrationForm.jsx
Labels: enhancement

#67 Update to Web config
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/controllers/AuthenticationController.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/WebConfig.java
Labels: enhancement

#68 Update Authentication and Registration file structure
  Show-MO-events/src/App.jsx
  Show-MO-events/src/components/loginForm/Google.css
  Show-MO-events/src/components/loginForm/GoogleButton.jpg
  Show-MO-events/src/components/loginForm/GoogleLogin.jsx
  Show-MO-events/src/components/loginForm/LoginForm.jsx
  Show-MO-events/src/components/passwordReset/PasswordResetForm.jsx
  Show-MO-events/src/components/registrationForm/RegistrationForm.jsx
Labels: enhancement

#69 Password Reset Addition.
  Show-MO-events-BackEnd/.gradle/8.8/executionHistory/executionHistory.bin
  Show-MO-events-BackEnd/.gradle/8.8/executionHistory/executionHistory.lock
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/fileHashes.bin
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/fileHashes.lock
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/resourceHashesCache.bin
  Show-MO-events-BackEnd/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  Show-MO-events-BackEnd/.gradle/buildOutputCleanup/outputFiles.bin
  Show-MO-events-BackEnd/.gradle/file-system.probe
  Show-MO-events-BackEnd/build/classes/java/main/org/launchcode/BackEnd/controllers/AuthenticationController.class
  Show-MO-events-BackEnd/build/classes/java/main/org/launchcode/BackEnd/models/User.class
  Show-MO-events-BackEnd/build/tmp/compileJava/previous-compilation-data.bin
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/controllers/AuthenticationController.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/User.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/WebConfig.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/dto/ResetPasswordDTO.java
  Show-MO-events/package-lock.json
  Show-MO-events/package.json
  Show-MO-events/src/components/passwordReset/PasswordResetForm.jsx
Labels: enhancement

#71 Aditional css for user auth
  Show-MO-events-BackEnd/.gradle/8.8/executionHistory/executionHistory.bin
  Show-MO-events-BackEnd/.gradle/8.8/executionHistory/executionHistory.lock
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/fileHashes.bin
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/fileHashes.lock
  Show-MO-events-BackEnd/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  Show-MO-events-BackEnd/.gradle/buildOutputCleanup/outputFiles.bin
  Show-MO-events-BackEnd/.gradle/file-system.probe
  Show-MO-events-BackEnd/build/tmp/compileJava/previous-compilation-data.bin
  Show-MO-events/package-lock.json
  Show-MO-events/src/components/loginForm/Google.css
  Show-MO-events/src/components/loginForm/Login.css
  Show-MO-events/src/components/loginForm/LoginForm.jsx
Labels: enhancement

#74 update to assist with pull request.
  Show-MO-events-BackEnd/.gradle/8.8/checksums/checksums.lock
  Show-MO-events-BackEnd/.gradle/8.8/checksums/md5-checksums.bin
  Show-MO-events-BackEnd/.gradle/8.8/checksums/sha1-checksums.bin
  Show-MO-events-BackEnd/.gradle/8.8/dependencies-accessors/gc.properties
  Show-MO-events-BackEnd/.gradle/8.8/executionHistory/executionHistory.bin
  Show-MO-events-BackEnd/.gradle/8.8/executionHistory/executionHistory.lock
  Show-MO-events-BackEnd/.gradle/8.8/fileChanges/last-build.bin
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/fileHashes.bin
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/fileHashes.lock
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/resourceHashesCache.bin
  Show-MO-events-BackEnd/.gradle/8.8/gc.properties
  Show-MO-events-BackEnd/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  Show-MO-events-BackEnd/.gradle/buildOutputCleanup/cache.properties
  Show-MO-events-BackEnd/.gradle/buildOutputCleanup/outputFiles.bin
  Show-MO-events-BackEnd/.gradle/file-system.probe
  Show-MO-events-BackEnd/build/tmp/compileJava/previous-compilation-data.bin
  Show-MO-events/src/services/AxiosService.js
Labels: enhancement

#72 New event backend
  Show-MO-events-BackEnd/build/resources/main/application.properties
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/controllers/EventCategoryController.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/controllers/EventController.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/Event.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/EventCategory.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/EventDetails.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/data/EventCategoryRepository.java
  Show-MO-events-BackEnd/src/main/resources/application.properties
  Show-MO-events/package.json
  Show-MO-events/src/App.jsx
  Show-MO-events/src/components/Google.css
  Show-MO-events/src/components/GoogleButton.jpg
  Show-MO-events/src/components/GoogleLogin.jsx
  Show-MO-events/src/components/Header.jsx
  Show-MO-events/src/pages/CreateEvent.jsx
  Show-MO-events/src/pages/EventManager.jsx
  Show-MO-events/src/pages/LandingPage.jsx
Labels: enhancement

#76 resolve issues
  Show-MO-events-BackEnd/.gradle/buildOutputCleanup/cache.properties
  Show-MO-events-BackEnd/build/tmp/compileTestJava/previous-compilation-data.bin
  Show-MO-events/src/App.jsx
  Show-MO-events/src/pages/CreatePost.jsx
Labels: enhancement, Dependency/Property Addition

#77 Reset password works again.
  Show-MO-events/src/App.jsx
Labels: enhancement

#80 Update App.jsx with new nav bar links!
  Show-MO-events-BackEnd/.gradle/8.8/checksums/checksums.lock
  Show-MO-events-BackEnd/.gradle/8.8/checksums/md5-checksums.bin
  Show-MO-events-BackEnd/.gradle/8.8/checksums/sha1-checksums.bin
  Show-MO-events-BackEnd/.gradle/8.8/executionHistory/executionHistory.bin
  Show-MO-events-BackEnd/.gradle/8.8/executionHistory/executionHistory.lock
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/fileHashes.bin
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/fileHashes.lock
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/resourceHashesCache.bin
  Show-MO-events-BackEnd/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  Show-MO-events-BackEnd/.gradle/buildOutputCleanup/outputFiles.bin
  Show-MO-events-BackEnd/.gradle/file-system.probe
  Show-MO-events-BackEnd/build.gradle
  Show-MO-events-BackEnd/build/classes/java/main/org/launchcode/BackEnd/controllers/AuthenticationController.class
  Show-MO-events-BackEnd/build/classes/java/main/org/launchcode/BackEnd/models/AbstractEntity.class
  Show-MO-events-BackEnd/build/classes/java/main/org/launchcode/BackEnd/models/User.class
  Show-MO-events-BackEnd/build/resources/main/static/css/bootstrap.css
  Show-MO-events-BackEnd/build/resources/main/templates/fragments.html
  Show-MO-events-BackEnd/build/resources/main/templates/index.html
  Show-MO-events-BackEnd/build/resources/main/templates/login.html
  Show-MO-events-BackEnd/build/resources/main/templates/register.html
  Show-MO-events-BackEnd/build/tmp/compileJava/previous-compilation-data.bin
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/config/WebConfig.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/config/WebSecurityConfig.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/controllers/AuthenticationController.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/controllers/CommentController.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/controllers/PostController.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/controllers/SearchController.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/AbstractEntity.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/Comment.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/Post.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/User.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/data/CommentRepository.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/data/PostRepository.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/dto/CommentDTO.java
  Show-MO-events-BackEnd/src/main/resources/static/css/bootstrap.css
  Show-MO-events-BackEnd/src/main/resources/templates/fragments.html
  Show-MO-events-BackEnd/src/main/resources/templates/index.html
  Show-MO-events-BackEnd/src/main/resources/templates/login.html
  Show-MO-events-BackEnd/src/main/resources/templates/register.html
  Show-MO-events/package-lock.json
  Show-MO-events/package.json
  Show-MO-events/src/App.css
  Show-MO-events/src/App.jsx
  Show-MO-events/src/Comments.jsx
  Show-MO-events/src/EditPostForm.jsx
  Show-MO-events/src/PostForm.jsx
  Show-MO-events/src/PostList.jsx
  Show-MO-events/src/Routes.jsx
  Show-MO-events/src/SearchProfile.css
  Show-MO-events/src/SearchProfile.jsx
  Show-MO-events/src/UserProfile.jsx
  Show-MO-events/src/components/loginForm/LoginForm.jsx
  Show-MO-events/src/index.html
  Show-MO-events/src/main.jsx
  package-lock.json
Labels: enhancement

#82 New branch for the update login
  Show-MO-events-BackEnd/.gradle/8.8/executionHistory/executionHistory.lock
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/fileHashes.lock
  Show-MO-events-BackEnd/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  Show-MO-events-BackEnd/.gradle/buildOutputCleanup/outputFiles.bin
  Show-MO-events/package-lock.json
  Show-MO-events/src/App.jsx
  Show-MO-events/src/components/Google.css
  Show-MO-events/src/components/GoogleButton.jpg
  Show-MO-events/src/components/GoogleLogin.jsx
  Show-MO-events/src/components/Header.jsx
  Show-MO-events/src/components/logOut/LogOutAction.jsx
  Show-MO-events/src/components/loginForm/LoginForm.jsx
Labels: enhancement

#86 Full working features
  Show-MO-events-BackEnd/.gradle/8.8/executionHistory/executionHistory.bin
  Show-MO-events-BackEnd/.gradle/8.8/executionHistory/executionHistory.lock
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/fileHashes.bin
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/fileHashes.lock
  Show-MO-events-BackEnd/.gradle/8.8/fileHashes/resourceHashesCache.bin
  Show-MO-events-BackEnd/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  Show-MO-events-BackEnd/.gradle/file-system.probe
  Show-MO-events-BackEnd/build/classes/java/main/org/launchcode/BackEnd/controllers/AuthenticationController.class
  Show-MO-events-BackEnd/build/tmp/compileJava/previous-compilation-data.bin
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/config/RestTemplateConfig.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/controllers/AuthenticationController.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/controllers/EventController.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/controllers/SearchController.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/AbstractEntity.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/Event.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/User.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/data/UserRepository.java
  Show-MO-events/src/App.jsx
  Show-MO-events/src/SearchProfile.css
  Show-MO-events/src/SearchProfile.jsx
  Show-MO-events/src/UserProfile.jsx
  Show-MO-events/src/components/logOut/LogOutAction.jsx
  Show-MO-events/src/components/loginForm/LoginForm.jsx
  Show-MO-events/src/pages/EventManager.jsx
Labels: bug, enhancement

#88 Full function except post
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/data/UserRepository.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/dto/LoginFormDTO.java
  Show-MO-events-BackEnd/src/main/java/org/launchcode/BackEnd/models/dto/RegisterFormDTO.java
  Show-MO-events/src/App.jsx
  Show-MO-events/src/PostForm.jsx
  Show-MO-events/src/PostList.jsx
  Show-MO-events/src/Routes.jsx
  Show-MO-events/src/components/logOut/LogOutAction.jsx
  Show-MO-events/src/components/loginForm/Google.css
  Show-MO-events/src/components/loginForm/GoogleLogin.jsx
  Show-MO-events/src/components/loginForm/LoginForm.jsx
  Show-MO-events/src/components/passwordReset/PasswordResetForm.jsx
  Show-MO-events/src/pages/Myprofile.jsx
Labels: enhancement
